name: Docker Image CI

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: git checkout 
        uses: actions/checkout@v3

      - name: genarating wp-config.php
        run: |
          cp ./wp-config-sample.php ./wp-config.php
          sed -ri -e 's!database_name_here!${{ secrets.DATABASE_NAME }}!g' ./wp-config.php
          sed -ri -e 's!username_here!${{ secrets.DATABASE_USERNAME }}!g' ./wp-config.php
          sed -ri -e 's!password_here!${{ secrets.DATABASE_PASSWORD }}!g' ./wp-config.php
          sed -ri -e 's!localhost!${{ secrets.DATABASE_HOST }}!g' ./wp-config.php
          ls -la

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: hemant19092/wordpressproject:latest

      
