name: Docker Image CI

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: git checkout 
        uses: actions/checkout@v3

      - name: genarating wp-config.php
        run: |
          rm -rf ./wp-config.php
          cp ./wp-config-sample.php ./wp-config.php
          sed -ri -e 's!database_name_here!${{ secrets.DATABASE_NAME }}!g' ./wp-config.php
          sed -ri -e 's!username_here!${{ secrets.DATABASE_USERNAME }}!g' ./wp-config.php
          sed -ri -e 's!password_here!${{ secrets.DATABASE_PASSWORD }}!g' ./wp-config.php
          sed -ri -e 's!localhost!${{ secrets.DATABASE_HOST }}!g' ./wp-config.php
          ls -la
          cat ./wp-config.php
      
      - name: Login to Docker Hub
        run: |
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        run: |
          docker build . -t hemant19092/wordpressproject:latest
          docker push hemant19092/wordpressproject:latest

      - name: Deploy Helm
        uses: bitovi/github-actions-deploy-eks-helm@v1.2.2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          cluster-name: wordpress-eks-cluster
          config-files: helm/values.yaml
          chart-path: helm/
          namespace: default
          name: wordpress
